name: URLTEST

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0/2 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    # - name: Timezone
    #   run: sudo timedatectl set-timezone 'Asia/Shanghai'
    - name: git config
      run: git config --local user.name "GitHub Actions"; git config --local user.email "actions@github.com"
    
    - name: pull pwc
      uses: actions/checkout@v4
      with:
        repository: kSLAWIASCA/pwcd
        token: ${{ secrets.privates }}
        path: pwc

    - name: run pipeline
      run: |
        cd pwc
        bash run_pipeline.sh

    # - name: pull actions
    #   uses: actions/checkout@v4
    #   with:
    #     repository: kSLAWIASCA/actions
    #     token: ${{ secrets.privates }}
    #     path: actions

    # - name: copy files
    #   run: |
    #     pwd
    #     cd actions && pwd
    #     cp ../pwc/clash.yml ./Clash.yml
    #     cp ../pwc/singbox*.json ./

    # # - name: Remove pwc directory
    # #   run: rm -rf pwc

    # - name: push to actions
    #   run: |
    #     pwd
    #     cd actions
    #     git config --local user.name "GitHub Actions"
    #     git config --local user.email "actions@github.com"
    #     git pull origin main
    #     git merge main
    #     git add .
    #     git commit -m "$(date '+%Y.%m.%d %H:%M:%S') update"
    #     git push origin main


